wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.10
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.6.12
    start_time: 1677506578.135727
    t:
      1:
      - 2
      - 3
      - 55
      2:
      - 2
      - 3
      - 55
      3:
      - 3
      - 8
      - 13
      - 23
      4: 3.6.12
      5: 0.13.10
      8:
      - 1
      - 3
      - 5
